name: "release"

on:
  release:
    types: [created]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - uses: cachix/cachix-action@v10
      with:
        name: ninegua
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: make nix-build
    - uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '*.wasm'
